### PR TITLE
some reference fixes

### PR DESCRIPTION
**Pull request by cgreene**

### CODE REVIEW

**Comment by cgreene** [comment]
The versioned DOI links don't work with crossref, so manubot can't get metadata from them. This is one batch. There may be more. Perhaps wait a bit to merge while I'm iteratively working on this 😁

**Comment by cgreene** [comment]
Ok! This is ready for a look when you are ready - thanks!

**Comment by cornhundred** [comment]
yeah, I've been dropping the version from the DOI.

**Comment by cornhundred** [comment]
thanks!

**Pull request merged**
