### PR TITLE
Propose Formatting

### PR DESCRIPTION
**Pull request by cgreene**
Would it be possible to use headers for formatting? This would help me cat things together and manubot has the capability to produce a table of contents by header, so folks could click right to these in the appendix.

### CODE REVIEW

**Comment by cornhundred** [comment]
Thanks for the edits. The reviews are being written as word documents and being converted to markdown using pandoc so we'll need to figure out how to get a good mapping working between the two. I'm thinking that we'll have a word doc template that converts to markdown in the way that we want and then we'll make sure new reviews are written using this template.

**Comment by cornhundred** [comment]
hi @cgreene, Nicolas wants to change the default template to this (ignore lack of headers etc I jut copied from word).

```
### Title
First Author et al. Journal/preprint server [@doi:10.1101/2020.01.28.923011]

#### Keywords
- Keyword 1
- Keyword 2
- Keyword 3

#### Main Findings
What were the primary findings

#### Limitations
What limitations exist

#### Significance
Significance of the findings 

#### Credit
Reviewed by YourNameHereOrRemove as part of a project by students, postdocs and faculty at the Immunology Institute of the Icahn School of Medicine, Mount Sinai.
```
Let me know if this is going to be an issue. I can help out with any reformatting issues :)

**Comment by cgreene** [comment]
I posted this in the gitter too:

@cornhundred : will you be maintaining the headers?
the headers are how we can get a table of contents for that appendix via manubot magic ( @agitter and more :-D )
I think that a `###` header for each paper and identical `####` subheaders for each section within it will be the way to go. These make it navigable and will let us plug into table of contents infrastructure in manubot

**Comment by cornhundred** [comment]
Yeah, I'll be maintaining the headers. Just out of lazyness I didn't add them (I'll show them above). Nicolas from Sinai wants to modify the subheaders.

**Comment by cornhundred** [comment]
Although it also looks like you all want to split this 

```
First Author et al. Journal/preprint server [@doi:10.1101/2020.01.28.923011]
```

into two lines

```
First Author et al. Journal/preprint server
[@doi:10.1101/2020.01.28.923011]
```

**Comment by cgreene** [comment]
Ok! Two lines will actually format exactly the same for us so that doesn't make a difference on how things will look on our side 😁

**Comment by cornhundred** [comment]
Great, so I'll put this as the preferred format in the README.md

**Pull request merged**
